theme: jekyll-theme-slate
title: Slash command for http://milujipraci.cz
description: Slash command allowing user to use punch lines form famous milujipraci.cz right in his IM platform such as Slack or Mattermost.
